// Generated by gencpp from file first_coursework/Intention.msg
// DO NOT EDIT!


#ifndef FIRST_COURSEWORK_MESSAGE_INTENTION_H
#define FIRST_COURSEWORK_MESSAGE_INTENTION_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace first_coursework
{
template <class ContainerAllocator>
struct Intention_
{
  typedef Intention_<ContainerAllocator> Type;

  Intention_()
    : state()
    , distance(0.0)  {
    }
  Intention_(const ContainerAllocator& _alloc)
    : state(_alloc)
    , distance(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _state_type;
  _state_type state;

   typedef float _distance_type;
  _distance_type distance;





  typedef boost::shared_ptr< ::first_coursework::Intention_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::first_coursework::Intention_<ContainerAllocator> const> ConstPtr;

}; // struct Intention_

typedef ::first_coursework::Intention_<std::allocator<void> > Intention;

typedef boost::shared_ptr< ::first_coursework::Intention > IntentionPtr;
typedef boost::shared_ptr< ::first_coursework::Intention const> IntentionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::first_coursework::Intention_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::first_coursework::Intention_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::first_coursework::Intention_<ContainerAllocator1> & lhs, const ::first_coursework::Intention_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state &&
    lhs.distance == rhs.distance;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::first_coursework::Intention_<ContainerAllocator1> & lhs, const ::first_coursework::Intention_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace first_coursework

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::first_coursework::Intention_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::first_coursework::Intention_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::first_coursework::Intention_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::first_coursework::Intention_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::first_coursework::Intention_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::first_coursework::Intention_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::first_coursework::Intention_<ContainerAllocator> >
{
  static const char* value()
  {
    return "24590d8657c7ac106e9b50d9c4efeb47";
  }

  static const char* value(const ::first_coursework::Intention_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x24590d8657c7ac10ULL;
  static const uint64_t static_value2 = 0x6e9b50d9c4efeb47ULL;
};

template<class ContainerAllocator>
struct DataType< ::first_coursework::Intention_<ContainerAllocator> >
{
  static const char* value()
  {
    return "first_coursework/Intention";
  }

  static const char* value(const ::first_coursework::Intention_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::first_coursework::Intention_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string state\n"
"float32 distance\n"
;
  }

  static const char* value(const ::first_coursework::Intention_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::first_coursework::Intention_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
      stream.next(m.distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Intention_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::first_coursework::Intention_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::first_coursework::Intention_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.state);
    s << indent << "distance: ";
    Printer<float>::stream(s, indent + "  ", v.distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FIRST_COURSEWORK_MESSAGE_INTENTION_H
